Feat take variable
FutureBaseEditor/CalculatorApp_OYU pull request #2
Opened 2023-04-25 20:30 UTC by DilaZerenYilmaz

2023-04-25 20:33 UTC, suhrab91 approved these changes

2023-04-25 20:36 UTC, suhrab91 requested changes
Seçilecek işlem türlerinin de eklenmesi gerekmiyor muydu? :D

2023-04-25 20:37 UTC, FutureBaseEditor commented on Program.cs
> +            double sayi1 = double.Parse(Console.ReadLine());
Değişken isimlerini proje genelinde EN olarak kullanıyoruz. Değişken isimlendirmelerini düzenleyebilir misin?

2023-04-25 20:40 UTC, Kilicmert55 submitted a review, later dismissed
Successful

2023-04-25 20:41 UTC, suhrab91 commented on Program.cs
> +            double sayi1 = double.Parse(Console.ReadLine());
EN derken hocam? Yani sayi1 yerine num1 gibi mi?

2023-04-25 20:47 UTC, FutureBaseEditor commented on Program.cs
> +            double sayi1 = double.Parse(Console.ReadLine());
Bize yazılan yorumları resolved a kendimiz çekmiyoruz. Yorum yazan kişinin çekmesini bekliyoruz. Düzeltmeleri yaptıktan sonra düzeltildi gibi mesajlar bırakabilirsin

2023-04-25 20:59 UTC, DilaZerenYilmaz commented on Program.cs
> +            double sayi1 = double.Parse(Console.ReadLine());
Kontrol edebilir misiniz?

2023-04-25 21:03 UTC, FutureBaseEditor commented on Program.cs
> +            double num1 = double.Parse(Console.ReadLine());
1 2 gibi sayısal karakterleri mümkün olduğunca kullanmıyoruz. num gibi kısaltmalar tercih etmiyoruz. firstNumber kullanabilirsin

2023-04-25 21:10 UTC, FutureBaseEditor commented on Program.cs
> +            Console.Write("İşlem türü seçiniz: ");
Metin Pascal Case olmalı sanırım. Kontrol eder misin? Eğer özellikle bu şekilde yazılması istenmişse bu yorumu resolved a çekebilirsin.

2023-04-25 21:13 UTC, suhrab91 submitted a review, later dismissed

2023-04-25 21:29 UTC, suhrab91 approved these changes

2023-04-25 21:47 UTC, DilaZerenYilmaz commented on Program.cs
> +            Console.Write("İşlem türü seçiniz: ");
Düzeltildi, kontrol edebilir misiniz?

2023-04-26 06:01 UTC, FutureBaseEditor approved these changes

2023-04-26 10:38 UTC, merged